#!/bin/bash

if [[ "$SOURCE_BRANCH" = "master" ]]
then
  docker build --build-arg BUILD_DATE=`date -u +%Y%m%d` --build-arg VERSION=master-${SOURCE_COMMIT} -t $IMAGE_NAME .
else
  docker build --build-arg BUILD_DATE=`date -u +%Y%m%d` --build-arg VERSION=${SOURCE_BRANCH} -t $IMAGE_NAME .
fi

